### ISSUE TITLE
no instaboostfast

### ISSUE THREAD

**Issue by cherryolg** [dragonlee258079/Saliency-Ranking#4]
“”from instaboostfast import get_new_data, InstaBoostConfig“”
hello,there is no "instaboostfast"
error`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\coding\Saliency-Ranking-main\detectron2\data\__init__.py", line 15, in <module>
    from .my_train_loader_build import build_rank_saliency_train_loader
  File "E:\coding\Saliency-Ranking-main\detectron2\data\my_train_loader_build.py", line 12, in <module>
    from .my_dataset_mapper import DatasetMapper
  File "E:\coding\Saliency-Ranking-main\detectron2\data\my_dataset_mapper.py", line 7, in <module>
    from instaboostfast import get_new_data, InstaBoostConfig
ModuleNotFoundError: No module named 'instaboostfast'`

**Comment by dragonlee258079** [comment]
It's a python package. You can use `pip install instaboostfast` command to install it.
